### ISSUE TITLE
In bestsqs.out-POSCAR, spacing between lattice vectors is missing

### ISSUE THREAD

**Issue by princego** [changning/sqs2poscar#1]
POSCAR
xxx
 -0.00000000-10.75900000 -5.65600000
  0.00000000 10.75900000 -5.65600000
 10.75900000  0.00000000  0.00000000

In line3, there is no space between -0.00000000 and -10.75900000
Could you please fix this issue?

**Comment by c-niu** [comment]
You can change the following two lines to increase the printing width to a higher value, e.g., `setw(15)` to avoid this issue:

https://github.com/changning/sqs2poscar/blob/1775443ada6d87e0f865f0ac003ea37f5fef38f9/sqs2poscar.cpp#L232

https://github.com/changning/sqs2poscar/blob/1775443ada6d87e0f865f0ac003ea37f5fef38f9/sqs2poscar.cpp#L246

**Comment by princego** [comment]
Thank you so much. I've fixed it.
